version: 2.1

jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - gems-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile.lock" }}
            - gems-v1-{{ .Environment.CIRCLE_JOB }}-
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: gems-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run tests
          command: bundle exec rake spec

workflows:
  test-matrix:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version:
                - "2.7"
                - "3.1"
                - "3.2"
                - "3.3"
                - "3.4"
